sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Zxa123456*
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tAmQrvTt1X16DrVEJuw
    access-key-secret: xX5kaHWODRS2vpHEoJfWkAda4dBRdZ
    bucket-name: zengxian-sky-take-out
  #文件上传保存目录(nginx 的 html/sky 目录下,返回 /img/upload/xxx 即可直接访问)
  redis:
    host: localhost
    port: 6379
    password: Zxa123456*
    database: 10
  upload:
    dir: D:/Develop/Project1/nginx-1.20.2/html/sky/img/upload
